# Generated by Django 4.2.6 on 2023-12-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_created_cart_paid_cart_paid_time_cart_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='paid_time',
        ),
    ]
