# Generated by Django 4.2.6 on 2023-11-25 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_alter_productphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like', '0002_alter_like_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'game')},
        ),
    ]
